src/main/java/itakademija/java2015/jpa/assigment1/entities/Address.java
package itakademija.java2015.jpa.assigment1.entities;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

@Embeddable
public class Address implements Serializable {
	private static final long serialVersionUID = -1276076195792170244L;

	
	private String country;
	private String city;
	private String street;
	private String building;
	private String flat;


	public String getCountry() {
		return country;
	}


	public void setCountry(String country) {
		this.country = country;
	}


	public String getCity() {
		return city;
	}


	public void setCity(String city) {
		this.city = city;
	}


	public String getStreet() {
		return street;
	}


	public void setStreet(String street) {
		this.street = street;
	}


	public String getBuilding() {
		return building;
	}


	public void setBuilding(String building) {
		this.building = building;
	}


	public String getFlat() {
		return flat;
	}


	public void setFlat(String flat) {
		this.flat = flat;
	}

	@Override
	public String toString() {
		return "Address [country=" + country + ", city=" + city + ", street=" + street + ", building="
				+ building + ", flat=" + flat + "]";
	}
}

src/main/java/itakademija/java2015/jpa/assigment1/entities/Author.java
package itakademija.java2015.jpa.assigment1.entities;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.DiscriminatorType;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotBlank;

@Entity
@Table(indexes = @Index(columnList = "name ASC, lastname DESC", name = "AUTH_NAME_IDX", unique=false) , name = "AUTHOR")
@DiscriminatorColumn(discriminatorType = DiscriminatorType.CHAR, length = 1, name = "AUTHOR_TYPE")
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorValue("G")
public class Author implements Serializable {

	private static final long serialVersionUID = 5089035398648855772L;
	@Id
	@GeneratedValue
	private Long id;
	@NotNull
	@NotBlank

	private String name;
	private String lastname;

	@OneToMany(mappedBy = "author", fetch = FetchType.EAGER, cascade = { CascadeType.ALL })
	private List<Book> books;

	@ManyToMany(cascade = {CascadeType.DETACH, CascadeType.MERGE, CascadeType.PERSIST, CascadeType.REFRESH}, fetch = FetchType.EAGER)
	private List<AuthorTag> tags;

	public List<AuthorTag> getTags() {
		return tags;
	}

	public void setTags(List<AuthorTag> tags) {
		this.tags = tags;
	}

	// @OneToOne(cascade=CascadeType.ALL)
	@Embedded
	private Address address;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Address getAddress() {
		return address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public List<Book> getBooks() {
		return books;
	}

	public void addBook(Book b) {
		if (getBooks() == null)
			setBooks(new ArrayList<>());
		if (!getBooks().contains(b))
			getBooks().add(b);
	}

	public void setBooks(List<Book> books) {
		this.books = books;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastname() {
		return lastname;
	}

	public void setLastname(String surname) {
		this.lastname = surname;
	}


	@Override
	public String toString() {
		return "Author [id=" + id + ", name=" + name + ", lastname=" + lastname + ", books=["
				+ ((books == null) ? books : books.size()) + "]" + ", address=" + address + "]" + super.toString();
	}

}

src/main/java/itakademija/java2015/jpa/assigment1/entities/AuthorTag.java
package itakademija.java2015.jpa.assigment1.entities;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entity implementation class for Entity: AuthorTag
 *
 */
@Entity
public class AuthorTag implements Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE)
	private Long id;
	
	@Column(nullable=false, unique=true)
	private String tag;
	@Temporal(TemporalType.TIMESTAMP)
	private Date createdOn;

	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public AuthorTag() {
		super();
	}   
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}   
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}
	
	@Override
	public String toString() {
		return "AuthorTag [id=" + id + ", tag=" + tag + ", createdOn=" + createdOn + "]";
	}
	
   
}

src/main/java/itakademija/java2015/jpa/assigment1/entities/Book.java
package itakademija.java2015.jpa.assigment1.entities;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotBlank;

@Entity
public class Book implements Serializable {
	private static final long serialVersionUID = -2592264505437536988L;
	@Id
	@GeneratedValue
	private Long id;
	@NotNull
	@NotBlank
	private String title;
	@Temporal(TemporalType.DATE)
	private Date releaseDate;
	/**
	 * Edition of the book; For example: "second", "2nd", "anniversary", ..
	 */
	private String edition;
	@JoinColumn(name = "author_id")
	@ManyToOne(optional = true, cascade = { CascadeType.ALL })
	private Author author;


	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Date getReleaseDate() {
		return releaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	public String getEdition() {
		return edition;
	}

	public void setEdition(String edition) {
		this.edition = edition;
	}

	public Author getAuthor() {
		return author;
	}

	public void setAuthor(Author author) {
		this.author = author;
		author.addBook(this);
	}

	@Override
	public String toString() {
		return "Book [id=" + id + ", title=" + title + ", releaseDate=" + releaseDate + ", edition=" + edition
				+ ", author=" + ((author == null) ? null : author.getName()) + "]" + super.toString();
	}
}

src/main/java/itakademija/java2015/jpa/assigment1/entities/FictionOnlyAuthor.java
package itakademija.java2015.jpa.assigment1.entities;

import javax.persistence.DiscriminatorColumn;
import javax.persistence.DiscriminatorType;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Table;

@Table(name="AUTHOR")
@DiscriminatorValue("F")
public class FictionOnlyAuthor extends Author {
	/**
	 * 
	 */
	private static final long serialVersionUID = -2161590463566713623L;
	private String nickNameInFictionCommunity;

	public String getNickNameInFictionCommunity() {
		return nickNameInFictionCommunity;
	}

	public void setNickNameInFictionCommunity(String nickNameInFictionCommunity) {
		this.nickNameInFictionCommunity = nickNameInFictionCommunity;
	}
	
}

src/main/java/itakademija/java2015/ui/controllers/AddNewBookPageBean.java
package itakademija.java2015.ui.controllers;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import itakademija.java2015.jpa.assigment1.entities.Author;
import itakademija.java2015.jpa.assigment1.entities.Book;
import itakademija.java2015.jpa.assigment1.entities.repositories.jpa.AuthorDaoImpl;
import itakademija.java2015.jpa.assigment1.entities.repositories.jpa.BookRepositoryJPA;

public class AddNewBookPageBean {
	static final Logger log = LoggerFactory.getLogger(AddNewBookPageBean.class);

	private AuthorDaoImpl authorRepo;
	private BookRepositoryJPA bookRepo;

	private AuthorsListPageBean authorsListPageBean;
	
	private Book newBook;
	
	public void init() {
		newBook = new Book();
	}
	
	public String addNew() {

		Author author = authorsListPageBean.getData().getCurrentAuthor();
		log.debug("Before saving book, got author: {}", author);
		log.debug("New book data: {}", newBook);
		newBook.setAuthor(author);
		author.addBook(newBook);
		authorRepo.save(author);
		
		return AuthorsListPageBean.NAV_LIST_AUTHORS;
	}
	
	public AuthorsListPageBean getAuthorsListPageBean() {
		return authorsListPageBean;
	}
	public void setAuthorsListPageBean(AuthorsListPageBean authorsListPageBean) {
		this.authorsListPageBean = authorsListPageBean;
	}
	public AuthorDaoImpl getAuthorRepo() {
		return authorRepo;
	}
	public void setAuthorRepo(AuthorDaoImpl authorRepo) {
		this.authorRepo = authorRepo;
	}
	public BookRepositoryJPA getBookRepo() {
		return bookRepo;
	}
	public void setBookRepo(BookRepositoryJPA bookRepo) {
		this.bookRepo = bookRepo;
	}
	public Book getNewBook() {
		return newBook;
	}
	public void setNewBook(Book newBook) {
		this.newBook = newBook;
	}
}

src/main/java/itakademija/java2015/ui/controllers/AuthorsListPageBean.java
package itakademija.java2015.ui.controllers;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.validation.Valid;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import itakademija.java2015.jpa.assigment1.entities.Author;
import itakademija.java2015.jpa.assigment1.entities.AuthorTag;
import itakademija.java2015.jpa.assigment1.entities.repositories.jpa.AuthorDaoImpl;

public class AuthorsListPageBean {
	private static final String NAV_SHOW_AUTHORS_BY_TAG = "show-tags";

	static final Logger log = LoggerFactory.getLogger(AuthorsListPageBean.class);

	public static final String NAV_SHOW_ADD_BOOK = "show-add-book";
	public static final String NAV_LIST_AUTHORS = "list-authors";


	public static class AuthorsListPageData implements Serializable {

		private static final long serialVersionUID = -7847613490719023414L;

		@Valid
		
		private Author newAuthor;


		@Valid
		private Author currentAuthor;

		private String tags;
		
		private String searchTag;
		
		private List<Author> foundAuthors;


		public void init() {
			newAuthor = new Author();
			foundAuthors = new ArrayList<>();
		}

		public String getSearchTag() {
			return searchTag;
		}

		public void setSearchTag(String searchTag) {
			this.searchTag = searchTag;
		}

		public List<Author> getFoundAuthors() {
			return foundAuthors;
		}

		public void setFoundAuthors(List<Author> foundAuthors) {
			this.foundAuthors = foundAuthors;
		}

		public String getTags() {
			return tags;
		}

		public void setTags(String tags) {
			this.tags = tags;
		}

		public Author getCurrentAuthor() {
			return currentAuthor;
		}

		public void setCurrentAuthor(Author currentAuthor) {
			this.currentAuthor = currentAuthor;
		}

		public Author getNewAuthor() {
			return newAuthor;
		}

		public void setNewAuthor(Author newAuthor) {
			this.newAuthor = newAuthor;
		}
	} 


	private AuthorsListPageData data;

	private AuthorDaoImpl authorRepo;

	public String addNew() {
		String tagsString = data.getTags();
		if (tagsString != null) {
			List<AuthorTag> tagList = convertTagStringToTagList(tagsString);

			data.newAuthor.setTags(tagList);
		}
		authorRepo.save(data.newAuthor);
		data.newAuthor = new Author();
		data.tags = "";
		return NAV_LIST_AUTHORS;
	}
	public String convertTagListToTagString(List<AuthorTag> tags) {
		String ret = "";
		for (AuthorTag tag: tags) {
			ret += tag.getTag() + " ";
		}
		return ret;
	}
	private List<AuthorTag> convertTagStringToTagList(String tagsString) {
		log.debug("Converting string[{}]", tagsString);
		List<AuthorTag> tagList = new ArrayList<>();

		if (tagsString != null) {
	
			String[] res = tagsString.split("\\s+");
			log.debug("Split size: {}", res.length);
			List<String> tagsArray = Arrays.asList(res);
			log.debug("List size:{}", tagsArray.size());
			for (String tagStr : tagsArray) {
				AuthorTag t = null;
				t = authorRepo.findTag(tagStr);
				if (t == null)
				{
					log.debug("New tag: {}", tagStr);
					t = new AuthorTag();
					t.setCreatedOn(new Date());
				}
				else
					log.debug("Existing tag: {}", tagStr);
				log.debug("Adding single tag: [{}]", tagStr);
				t.setTag(tagStr);
				tagList.add(t);
			}
		}
		return tagList;
	}

	public String deleteSelected(Author author) {
		if (author == null)
			FacesContext.getCurrentInstance().addMessage(null,
					new FacesMessage(FacesMessage.SEVERITY_WARN, "Warning!", "Author being deleted is null?"));
		else {
			if (author.getName().equalsIgnoreCase("Jonas"))
				FacesContext.getCurrentInstance().addMessage(null,
						new FacesMessage(FacesMessage.SEVERITY_INFO, "Info", "You are deleting Jonas!"));
			authorRepo.delete(author);
		}
		return NAV_LIST_AUTHORS;
	}


	public String showAddBookPage(Author a) {
		log.debug("Will store selected author for later access in Add new Book form: {}", a);
		data.currentAuthor = a;
		return NAV_SHOW_ADD_BOOK;
	}

	public String searchTags() {
		//save to session
		data.foundAuthors = authorRepo.findAllAuthorsByTag(data.getSearchTag());
		return NAV_SHOW_AUTHORS_BY_TAG;
	}
	public AuthorsListPageData getData() {
		return data;
	}

	public void setData(AuthorsListPageData data) {
		this.data = data;
	}

	public AuthorDaoImpl getAuthorRepo() {
		return authorRepo;
	}

	public void setAuthorRepo(AuthorDaoImpl authorRepo) {
		this.authorRepo = authorRepo;

	}

	public List<Author> getAuthorList() {
		return authorRepo.findAll();
	}
}

src/main/webapp/addBook.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets" template="sablonas.xhtml">

	<ui:define name="turinys">
		<h:form>
			<p:messages id="messages" showDetail="true" autoUpdate="true"
				closable="true" />
			<p:panel id="basic" header="Book details" style="margin-bottom:20px">
				<h:panelGrid id="grid" columns="3" cellpadding="5">
					<h:outputLabel for="bookTitle" value="Book title"></h:outputLabel>
					<h:inputText id="bookTitle" value="#{addBookPage.newBook.title}">
						<f:validateBean />
					</h:inputText>
					<p:message for="bookTitle" />
					<h:outputLabel for="bookReleaseDate"
						value="Book release date (YYY-MM-DD)"></h:outputLabel>

					<h:inputText id="bookReleaseDate"
						value="#{addBookPage.newBook.releaseDate}"
						converterMessage="Use format YYYY-MM-DD">
						<f:convertDateTime pattern="yyyy-M-d" />
					</h:inputText>
					<p:message for="bookReleaseDate" />
				</h:panelGrid>

				<h:commandButton action="#{addBookPage.addNew}" value="Add new"></h:commandButton>
			</p:panel>
		</h:form>

	</ui:define>

	<ui:define name="pavadinimas">
 	 	Add new book
 	 </ui:define>

</ui:composition>

src/main/webapp/authors.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets" template="sablonas.xhtml">

	<ui:define name="turinys">
		<h:form>
			
			<p:messages id="messages" showDetail="false" autoUpdate="true"
				closable="true" />

			<p:dataTable value="#{authorListPage.authorList}" var="author">
				<p:column headerText="Id">
					<h:outputText value="#{author.id}" />
				</p:column>

				<p:column headerText="Name">
					<h:outputText value="#{author.name}" />
				</p:column>

				<p:column headerText="Lastname">
					<h:outputText value="#{author.lastname}" />
				</p:column>

				<p:column headerText="Books">
					<h:dataTable value="#{author.books}" var="book" border="0">
						<h:column>
		  						#{book.title} (#{book.releaseDate})
	  					</h:column>
					</h:dataTable>
				</p:column>
				<p:column headerText="Tags">
					<h:outputText
						value="#{authorListPage.convertTagListToTagString(author.tags)}" />
				</p:column>

				<p:column headerText="">
					<h:commandButton value="Delete"
						action="#{authorListPage.deleteSelected(author)}" />
					<h:commandButton value="Add Book"
						action="#{authorListPage.showAddBookPage(author)}" />
				</p:column>
			</p:dataTable>


		</h:form>
		<h:form>
			<p:panel id="basic" header="Author" style="margin-bottom:20px">
				<h:panelGrid id="grid" columns="3" cellpadding="5">
					<h:outputLabel for="author_name" value="Author name"></h:outputLabel>
					<h:inputText id="author_name"
						value="#{authorListPageData.newAuthor.name}">
						<f:validateBean />
					</h:inputText>
					<p:message for="author_name" />

					<h:outputLabel for="author_lastname" value="Author lastname"></h:outputLabel>
					<h:inputText id="author_lastname"
						value="#{authorListPageData.newAuthor.lastname}"></h:inputText>
					<p:message for="author_lastname" display="icon" />
					<h:outputLabel for="tags" value="Author tags"></h:outputLabel>
					<h:inputText id="tags" value="#{authorListPageData.tags}"></h:inputText>
					<p:message for="tags" display="icon" />
				</h:panelGrid>

			</p:panel>

			<h:commandButton action="#{authorListPage.addNew}" value="Add new"
				update="grid"></h:commandButton>
		</h:form>

	</ui:define>

	<ui:define name="pavadinimas">
 	 	Add new book
 	 </ui:define>

</ui:composition>

src/main/webapp/sablonas.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
	<title>Mano puslapis - <ui:insert name="pavadinimas">
  		Pavadinimo nera
  	</ui:insert>
	</title>
	<!--   <h:outputStylesheet library="mano" name="failas.css"></h:outputStylesheet> -->
</h:head>
<h:body>
	<div id="container">
		<h:form>
			<p:tabMenu>
				<p:menuitem value="Authors" outcome="list-authors"
					icon="ui-icon-star">
				</p:menuitem>
				<p:menuitem value="Tag search" outcome="search-tags" icon="ui-icon-star">
				</p:menuitem>
			</p:tabMenu>
		</h:form>
		<div id="contents">
			<ui:insert name="turinys">
		  		Turinio nera
		  	</ui:insert>
		</div>
	</div>
</h:body>
</html>

src/main/webapp/tags.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets" template="sablonas.xhtml">

	<ui:define name="turinys">
		<h:form>

			<p:dataTable value="#{authorListPageData.foundAuthors}" var="author">
				<p:column headerText="Author name">
					<h:outputText value="#{author.name} #{author.lastname}" />
				</p:column>

			</p:dataTable>
		</h:form>
		
		<h:form>
			<p:panel id="basic" header="Search" style="margin-bottom:20px">
				<h:panelGrid id="grid" columns="3" cellpadding="5">
					<h:outputLabel for="tagSerach" value="Tag"></h:outputLabel>
					<h:inputText id="tagSerach"
						value="#{authorListPageData.searchTag}">
						<f:validateBean />
					</h:inputText>
					<p:message for="tagSerach" />
				</h:panelGrid>

			</p:panel>

			<h:commandButton action="#{authorListPage.searchTags}" value="Search"
				update="grid"></h:commandButton>
		</h:form>

	</ui:define>

	<ui:define name="pavadinimas">
 	 	Search tags
 	 </ui:define>

</ui:composition>